import json
from pathlib import Path

from agno.tools import Tool


@Tool
def template_loader_tool(
    template_name: str = "default",
) -> str:
    """Load blog template from file system"""
    try:
        templates_dir = Path("templates")
        templates_dir.mkdir(exist_ok=True)

        template_path = (
            templates_dir / f"{template_name}.json"
        )

        if template_path.exists():
            with open(
                template_path, "r", encoding="utf-8"
            ) as f:
                template_data = json.load(f)
                return template_data.get("content", "")

        # Fallback to default template if not found
        default_template = {
            "id": "default",
            "name": "Default Blog Template",
            "content": "# {title}\n\n{content}\n\n---\n*Source: {url}*\n*Generated by Agno Blog*",
            "version": "1.0.0",
        }

        # Save default template
        with open(
            template_path, "w", encoding="utf-8"
        ) as f:
            json.dump(
                default_template,
                f,
                indent=2,
                ensure_ascii=False,
            )

        return default_template["content"]

    except Exception as e:
        return f"Error loading template: {str(e)}"
